name: Prettier Check

on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  prettier-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@9a9194f87191a7e9055e3e9b95b8cfb13023bb08

      - name: Setup Node.js environment
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: npm ci

      - name: Prettier Check
        run: npx prettier --check .
